contribution charts: the compile errors are fixed but the
label provider is null?

org.eclipse.core.runtime.AssertionFailedException: assertion failed:
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.jface.viewers.ColumnViewer.setLabelProvider(ColumnViewer.java:347)
	at org.openlca.app.viewers.combo.AbstractComboViewer.createViewer(AbstractComboViewer.java:38)
	at org.openlca.app.viewers.combo.AbstractComboViewer.createViewer(AbstractComboViewer.java:1)
	at org.openlca.app.viewers.AbstractViewer.<init>(AbstractViewer.java:26)
	at org.openlca.app.viewers.combo.AbstractComboViewer.<init>(AbstractComboViewer.java:18)
	at org.openlca.app.components.ResultFlowCombo.<init>(ResultFlowCombo.java:28)
	at org.openlca.app.results.contributions.ContributionChartSection.createCombo(ContributionChartSection.java:73)