so I think this error was related to the plugin mix of the platform
```
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-09-25 15:04:52.267
!MESSAGE Unable to create class
'org.eclipse.ui.internal.e4.compatibility.CompatibilityView' from bundle
'78'
!STACK 0
org.eclipse.e4.core.di.InjectionException:
java.lang.NoClassDefFoundError: org/eclipse/jface/resource/ResourceLocator
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:422)
...
Caused by: java.lang.NoClassDefFoundError:
org/eclipse/jface/resource/ResourceLocator
        at org.eclipse.ui.internal.navigator.CommonNavigatorActionGroup.makeActions(CommonNavigatorActionGroup.java:131)
...
Caused by: java.lang.ClassNotFoundException:
org.eclipse.jface.resource.ResourceLocator cannot be found by
org.eclipse.ui.navigator_3.9.0.v20190807-2204
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)

!ENTRY org.eclipse.e4.ui.workbench.swt 4 2 2019-09-25 15:04:52.826
!MESSAGE Problems occurred when invoking code from plug-in:
"org.eclipse.e4.ui.workbench.swt".
!STACK 0
java.lang.NullPointerException
        at org.eclipse.ui.navigator.CommonNavigator.isDirty(CommonNavigator.java:668)
        at org.eclipse.ui.internal.WorkbenchPage.getDirtyParts(WorkbenchPage.java:3548)
```

now, everything comes from update sites and the build works (at least on
Windows)

and I always forget this:

```xml
<configurations>
   <plugin id="org.apache.felix.scr" autoStart="true" startLevel="2" />
   <plugin id="org.eclipse.core.runtime" autoStart="true" startLevel="4"
/>
   <plugin id="org.eclipse.equinox.common" autoStart="true"
startLevel="2" />
   <plugin id="org.eclipse.equinox.event" autoStart="true"
startLevel="2" />
</configurations>
```